/**
 * ConfigWizard — state machine logic tests
 *
 * Ink component testing requires a TTY, so we test the data layer:
 * - State transition validity (Cloud path, Esc back-navigation)
 * - Config file generation for all 8 cloud providers
 * - Edge cases (empty API key, no active models, whitespace trimming)
 */

import { describe, it, expect } from 'vitest'
import { DEFAULT_PROVIDERS, OLLAMA_PRESET_MODELS } from '../../src/shared/constants'
import { mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import type { ModelInfo } from '../../src/shared/types'

// ── Replicas of ConfigWizard logic (production code, inlined for testing) ──

const CLOUD_PROVIDERS = DEFAULT_PROVIDERS.filter((p) => p.id !== 'ollama' && p.id !== 'mipham')

function getActiveModels(providerId: string): ModelInfo[] {
  const provider = DEFAULT_PROVIDERS.find((p) => p.id === providerId)
  return provider?.models.filter((m) => m.status === 'active') || []
}

function writeConfigFile(
  providerId: string,
  modelId: string,
  apiKey: string,
  configDir: string,
): string {
  mkdirSync(configDir, { recursive: true })
  const provider = DEFAULT_PROVIDERS.find((p) => p.id === providerId)
  const models = getActiveModels(providerId)
  const lines = [
    '# Mipham Code Configuration',
    `# Generated by Config Wizard — ${new Date().toISOString()}`,
    '',
    'version: 1',
    `defaultProvider: ${providerId}`,
    `defaultModel: ${modelId}`,
    'permission: default',
    '',
    'providers:',
    `  - id: ${providerId}`,
    `    name: ${provider?.name || providerId}`,
    `    protocol: ${provider?.protocol || 'openai-compatible'}`,
    ...(provider?.baseUrl ? [`    baseUrl: ${provider.baseUrl}`] : []),
    `    apiKey: ${apiKey}`,
    `    models:`,
    ...models.map((m) => `      - id: ${m.id}`),
  ]

  const content = lines.join('\n')
  writeFileSync(join(configDir, 'config.yml'), content, 'utf-8')
  return content
}

type Step = 'welcome' | 'mode' | 'provider' | 'model' | 'apikey' | 'ollama' | 'confirm' | 'done'

// Simulate the state machine: returns the next step given current step + action
function transition(
  step: Step,
  action: 'enter' | 'escape' | 'up' | 'down',
  context?: { mode?: 'cloud' | 'local'; cursor?: number; maxItems?: number },
): Step {
  // Esc back-navigation
  if (action === 'escape') {
    const backMap: Record<Step, Step> = {
      welcome: 'welcome', // onSkip() — stays, handled by parent
      mode: 'welcome',
      provider: 'mode',
      model: 'provider',
      apikey: 'model',
      ollama: 'mode',
      confirm: context?.mode === 'cloud' ? 'apikey' : 'ollama',
      done: 'done',
    }
    return backMap[step]
  }

  // Enter — forward navigation
  if (action === 'enter') {
    const forwardMap: Record<Step, Step> = {
      welcome: 'mode',
      mode: context?.mode === 'cloud' ? 'provider' : 'ollama',
      provider: 'model',
      model: 'apikey',
      apikey: 'confirm',
      ollama: 'confirm',
      confirm: 'done',
      done: 'done',
    }
    return forwardMap[step]
  }

  // Arrow keys — stay on same step (cursor moves, not step)
  return step
}

// ── Tests ──

describe('ConfigWizard Cloud path', () => {
  // ─── Provider / model data ───

  describe('CLOUD_PROVIDERS', () => {
    it('excludes ollama and mipham', () => {
      const ids = CLOUD_PROVIDERS.map((p) => p.id)
      expect(ids).not.toContain('ollama')
      expect(ids).not.toContain('mipham')
    })

    it('has exactly 8 cloud providers', () => {
      expect(CLOUD_PROVIDERS).toHaveLength(8)
    })

    it('all providers have at least 1 active model', () => {
      for (const p of CLOUD_PROVIDERS) {
        const active = getActiveModels(p.id)
        expect(
          active.length,
          `${p.name} has no active models — model step would be empty`,
        ).toBeGreaterThan(0)
      }
    })

    it('all providers have a name and protocol', () => {
      for (const p of CLOUD_PROVIDERS) {
        expect(p.name).toBeTruthy()
        expect(p.protocol).toBeTruthy()
      }
    })
  })

  // ─── State machine transitions ───

  describe('Forward transitions (Enter key)', () => {
    it('welcome → mode', () => {
      expect(transition('welcome', 'enter')).toBe('mode')
    })

    it('mode → provider (Cloud)', () => {
      expect(transition('mode', 'enter', { mode: 'cloud' })).toBe('provider')
    })

    it('mode → ollama (Local)', () => {
      expect(transition('mode', 'enter', { mode: 'local' })).toBe('ollama')
    })

    it('provider → model', () => {
      expect(transition('provider', 'enter')).toBe('model')
    })

    it('model → apikey', () => {
      expect(transition('model', 'enter')).toBe('apikey')
    })

    it('apikey → confirm (TextInput onSubmit)', () => {
      expect(transition('apikey', 'enter')).toBe('confirm')
    })

    it('ollama → confirm', () => {
      expect(transition('ollama', 'enter')).toBe('confirm')
    })

    it('confirm → done (finishCloud)', () => {
      expect(transition('confirm', 'enter')).toBe('done')
    })

    it('done is terminal', () => {
      expect(transition('done', 'enter')).toBe('done')
    })

    it('complete Cloud path: welcome→mode→provider→model→apikey→confirm→done', () => {
      const path: Step[] = []
      let step: Step = 'welcome'
      path.push(step)

      step = transition(step, 'enter')
      expect(step).toBe('mode')
      path.push(step)

      step = transition(step, 'enter', { mode: 'cloud' })
      expect(step).toBe('provider')
      path.push(step)

      step = transition(step, 'enter')
      expect(step).toBe('model')
      path.push(step)

      step = transition(step, 'enter')
      expect(step).toBe('apikey')
      path.push(step)

      step = transition(step, 'enter')
      expect(step).toBe('confirm')
      path.push(step)

      step = transition(step, 'enter')
      expect(step).toBe('done')
      path.push(step)

      expect(path).toEqual(['welcome', 'mode', 'provider', 'model', 'apikey', 'confirm', 'done'])
    })
  })

  // ─── Esc back-navigation ───

  describe('Esc back-navigation', () => {
    it('mode → welcome', () => {
      expect(transition('mode', 'escape')).toBe('welcome')
    })

    it('provider → mode', () => {
      expect(transition('provider', 'escape')).toBe('mode')
    })

    it('model → provider', () => {
      expect(transition('model', 'escape')).toBe('provider')
    })

    it('apikey → model', () => {
      expect(transition('apikey', 'escape')).toBe('model')
    })

    it('ollama → mode', () => {
      expect(transition('ollama', 'escape')).toBe('mode')
    })

    it('confirm → apikey (cloud mode)', () => {
      expect(transition('confirm', 'escape', { mode: 'cloud' })).toBe('apikey')
    })

    it('confirm → ollama (local mode)', () => {
      expect(transition('confirm', 'escape', { mode: 'local' })).toBe('ollama')
    })

    it('full Esc back-path: confirm→apikey→model→provider→mode→welcome', () => {
      let step: Step = 'confirm'

      step = transition(step, 'escape', { mode: 'cloud' })
      expect(step).toBe('apikey')

      step = transition(step, 'escape')
      expect(step).toBe('model')

      step = transition(step, 'escape')
      expect(step).toBe('provider')

      step = transition(step, 'escape')
      expect(step).toBe('mode')

      step = transition(step, 'escape')
      expect(step).toBe('welcome')
    })
  })

  // ─── getActiveModels ───

  describe('getActiveModels', () => {
    it('returns only active models', () => {
      const models = getActiveModels('mipham')
      // MiphamAI models are all 'upcoming', not 'active'
      expect(models).toHaveLength(0)
    })

    it('returns all 6 Anthropic models as active', () => {
      const models = getActiveModels('anthropic')
      expect(models.length).toBeGreaterThanOrEqual(6)
      const ids = models.map((m) => m.id)
      expect(ids).toContain('claude-haiku-4-5-20251001')
      expect(ids).toContain('claude-opus-5')
    })

    it('returns empty array for unknown provider', () => {
      expect(getActiveModels('nonexistent')).toEqual([])
    })
  })

  // ─── writeConfigFile ───

  describe('writeConfigFile', () => {
    const tmpDir = join(tmpdir(), 'mipham-config-test-' + Date.now())

    it('generates valid config for all 8 cloud providers', () => {
      for (const provider of CLOUD_PROVIDERS) {
        const models = getActiveModels(provider.id)
        const testModel = models[0]!
        const testKey = `test-key-${provider.id}-abc123`

        const config = writeConfigFile(provider.id, testModel.id, testKey, tmpDir)

        // Structural assertions
        expect(config).toContain('version: 1')
        expect(config).toContain(`defaultProvider: ${provider.id}`)
        expect(config).toContain(`defaultModel: ${testModel.id}`)
        expect(config).toContain(`apiKey: ${testKey}`)
        expect(config).toContain(`name: ${provider.name}`)
        expect(config).toContain('permission: default')

        // Every active model is listed
        for (const m of models) {
          expect(config).toContain(`- id: ${m.id}`)
        }

        // File was actually written to disk
        const filePath = join(tmpDir, 'config.yml')
        const onDisk = readFileSync(filePath, 'utf-8')
        expect(onDisk).toBe(config)
      }
    })

    it('includes baseUrl for providers that have one', () => {
      const config = writeConfigFile('deepseek', 'deepseek-v4-pro', 'sk-test', tmpDir)
      expect(config).toContain('baseUrl: https://api.deepseek.com/v1')
    })

    it('does not include baseUrl for Anthropic (native protocol)', () => {
      const config = writeConfigFile('anthropic', 'claude-sonnet-5', 'sk-ant-test', tmpDir)
      expect(config).not.toContain('baseUrl:')
    })

    // Cleanup
    try {
      rmSync(tmpDir, { recursive: true, force: true })
    } catch {
      // best-effort cleanup
    }
  })

  // ─── Edge cases ───

  describe('Edge cases', () => {
    it('empty API key should be caught before write', () => {
      const apiKey = ''
      const providerId = 'anthropic'
      const modelId = 'claude-sonnet-5'
      const isValid = !(!providerId || !modelId || !apiKey.trim())
      expect(isValid).toBe(false)
    })

    it('whitespace-only API key should be caught', () => {
      const apiKey = '   '
      const providerId = 'anthropic'
      const modelId = 'claude-sonnet-5'
      const isValid = !(!providerId || !modelId || !apiKey.trim())
      expect(isValid).toBe(false)
    })

    it('API key with surrounding whitespace is trimmed', () => {
      const apiKey = '  sk-test-key-123  '
      expect(apiKey.trim()).toBe('sk-test-key-123')
    })

    it('missing providerId is caught', () => {
      const providerId = null
      const modelId = 'some-model'
      const apiKey = 'sk-valid'
      const isValid = !(!providerId || !modelId || !apiKey.trim())
      expect(isValid).toBe(false)
    })

    it('missing modelId is caught', () => {
      const providerId = 'anthropic'
      const modelId = null
      const apiKey = 'sk-valid'
      const isValid = !(!providerId || !modelId || !apiKey.trim())
      expect(isValid).toBe(false)
    })

    it('arrow keys do not change step (only cursor)', () => {
      // ↑↓ should stay on the same step — they only move the cursor
      expect(transition('provider', 'up')).toBe('provider')
      expect(transition('provider', 'down')).toBe('provider')
      expect(transition('mode', 'up')).toBe('mode')
      expect(transition('mode', 'down')).toBe('mode')
      expect(transition('model', 'up')).toBe('model')
      expect(transition('model', 'down')).toBe('model')
      expect(transition('ollama', 'up')).toBe('ollama')
      expect(transition('ollama', 'down')).toBe('ollama')
    })
  })
})

// ── Ollama model list helpers ──

interface OllamaModelItem {
  id: string
  source: 'local' | 'MiphamAI' | '热门'
}

function getOllamaModelList(installedModels: string[]): OllamaModelItem[] {
  const seen = new Set<string>()
  const result: OllamaModelItem[] = []

  // ollama list 返回的本地模型
  for (const name of installedModels) {
    if (!seen.has(name)) {
      seen.add(name)
      result.push({ id: name, source: 'local' })
    }
  }

  // 预置模型（去重）
  for (const preset of OLLAMA_PRESET_MODELS) {
    if (!seen.has(preset.id)) {
      seen.add(preset.id)
      result.push({ id: preset.id, source: preset.source as 'MiphamAI' | '热门' })
    }
  }

  return result
}

describe('ConfigWizard Ollama model list', () => {
  it('includes installed models before preset models', () => {
    const list = getOllamaModelList(['llama3.2', 'qwen2.5'])
    expect(list[0]!.id).toBe('llama3.2')
    expect(list[0]!.source).toBe('local')
    expect(list[1]!.id).toBe('qwen2.5')
    expect(list[1]!.source).toBe('local')
  })

  it('deduplicates — installed model overrides preset', () => {
    // qwen2.5:72b is similar but not exact match, so both should appear
    const list = getOllamaModelList(['qwen2.5:72b'])
    // Preset qwen2.5:72b should be deduplicated since it's in installedModels
    const qwenEntries = list.filter((m) => m.id === 'qwen2.5:72b')
    expect(qwenEntries).toHaveLength(1)
    expect(qwenEntries[0]!.source).toBe('local')
  })

  it('includes all preset models when no local models installed', () => {
    const list = getOllamaModelList([])
    const presetIds = OLLAMA_PRESET_MODELS.map((p) => p.id)
    for (const id of presetIds) {
      expect(list.find((m) => m.id === id)).toBeTruthy()
    }
  })

  it('preset models have correct source labels', () => {
    const list = getOllamaModelList([])
    for (const item of list) {
      if (item.source === 'local') {
        expect(item.source).toBe('local')
      } else {
        expect(['MiphamAI', '热门']).toContain(item.source)
      }
    }
  })

  it('returns empty array when both installed and presets are empty (edge case)', () => {
    // This tests the empty input — presets always exist, so this is theoretical
    const list = getOllamaModelList([])
    expect(list.length).toBeGreaterThan(0) // presets always fill in
  })

  it('ollamaCursor navigation wraps around', () => {
    const list = getOllamaModelList(['llama3.2', 'codellama'])
    const len = list.length

    // Wrap up from 0 → last
    const upFrom0 = 0 > 0 ? 0 - 1 : len - 1
    expect(upFrom0).toBe(len - 1)

    // Wrap down from last → 0
    const downFromLast = len - 1 < len - 1 ? len - 1 + 1 : 0
    expect(downFromLast).toBe(0)

    // Normal up
    const upFrom1 = 1 > 0 ? 1 - 1 : len - 1
    expect(upFrom1).toBe(0)

    // Normal down
    const downFrom0 = 0 < len - 1 ? 0 + 1 : 0
    expect(downFrom0).toBe(1)
  })

  it('MiphamAI preset models appear with [MiphamAI] label', () => {
    const list = getOllamaModelList([])
    const miphamModels = list.filter((m) => m.source === 'MiphamAI')
    expect(miphamModels.length).toBeGreaterThanOrEqual(1)
    expect(miphamModels[0]!.id).toContain('om-V5')
  })

  it('热门 preset models appear with [热门] label', () => {
    const list = getOllamaModelList([])
    const hotModels = list.filter((m) => m.source === '热门')
    expect(hotModels.length).toBeGreaterThanOrEqual(1)
    expect(hotModels.map((m) => m.id)).toContain('deepseek-r1:70b')
  })
})
