version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/react'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      - dependency-name: 'next'
        update-types: ['version-update:semver-major']
      - dependency-name: 'tailwindcss'
        update-types: ['version-update:semver-major']
      - dependency-name: 'ink'
        update-types: ['version-update:semver-major']
      - dependency-name: 'commander'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-devtools-core'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'actions/checkout'
        update-types: ['version-update:semver-major']
      - dependency-name: 'actions/setup-node'
        update-types: ['version-update:semver-major']
      - dependency-name: 'pnpm/action-setup'
        update-types: ['version-update:semver-major']
      - dependency-name: 'actions/upload-artifact'
        update-types: ['version-update:semver-major']
      - dependency-name: 'actions/download-artifact'
        update-types: ['version-update:semver-major']
      - dependency-name: 'softprops/action-gh-release'
        update-types: ['version-update:semver-major']
