#!/usr/bin/env bun
/**
 * Generate src/skills/bundled-skills.ts — an in-memory snapshot of the
 * built-in skills, embedded into the compiled binary.
 *
 * The standalone binary (`bun build --compile`) has no `skills/` directory on
 * disk, so the SkillsLoader falls back to this snapshot when its disk lookup
 * finds nothing. Regenerate whenever skills are added/removed/changed:
 *
 *   bun run scripts/generate-bundled-skills.ts
 *
 * The generated file is committed to the repo; a test fails CI if it drifts
 * from `skills/` on disk (single-source-of-truth guard).
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const CLI_ROOT = join(import.meta.dir, '..')
const SKILLS_DIR = join(CLI_ROOT, 'skills')
const OUTPUT_FILE = join(CLI_ROOT, 'src', 'skills', 'bundled-skills.ts')

interface BundledSkill {
  type: 'standard' | 'mipham'
  raw: string
}

function collect(dir: string, type: 'standard' | 'mipham', ext: string): BundledSkill[] {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(ext))
    .sort()
  return files.map((f) => ({
    type,
    raw: readFileSync(join(dir, f), 'utf-8'),
  }))
}

function main(): void {
  const standard = collect(join(SKILLS_DIR, 'standard'), 'standard', '.SKILL.md')
  const mipham = collect(join(SKILLS_DIR, 'mipham'), 'mipham', '.mipham-skill.md')
  const all = [...standard, ...mipham]

  const lines: string[] = [
    '// AUTO-GENERATED by scripts/generate-bundled-skills.ts — DO NOT EDIT.',
    '// Regenerate with: bun run scripts/generate-bundled-skills.ts',
    '// In-memory snapshot of the built-in skills, embedded into the compiled binary.',
    '',
    'export interface BundledSkill {',
    "  type: 'standard' | 'mipham'",
    '  raw: string',
    '}',
    '',
    'export const BUNDLED_SKILLS: ReadonlyArray<BundledSkill> = [',
  ]
  for (const s of all) {
    lines.push(`  { type: '${s.type}', raw: ${JSON.stringify(s.raw)} },`)
  }
  lines.push(']')
  lines.push('')

  writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8')
  console.log(
    `Generated ${OUTPUT_FILE} with ${all.length} skills (${standard.length} standard, ${mipham.length} mipham)`,
  )
}

main()
