#!/usr/bin/env bun
/**
 * Generate src/skills/bundled-skills.ts AND src/skills/bundled-skill-assets.ts —
 * in-memory snapshots embedded into the compiled binary.
 *
 * The standalone binary (`bun build --compile`) has no `skills/` directory on
 * disk, so the SkillsLoader falls back to these snapshots. `bundled-skill-assets.ts`
 * additionally carries the executable assets (scripts/references) of skills that
 * ship them (currently `web-access`), extracted to `~/.mipham/skills/<name>/` at
 * first use. Regenerate whenever skills or their assets are added/removed/changed:
 *
 *   bun run scripts/generate-bundled-skills.ts
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join } from 'node:path'

const CLI_ROOT = join(import.meta.dir, '..')
const SKILLS_DIR = join(CLI_ROOT, 'skills')
const OUTPUT_FILE = join(CLI_ROOT, 'src', 'skills', 'bundled-skills.ts')
const ASSETS_OUTPUT_FILE = join(CLI_ROOT, 'src', 'skills', 'bundled-skill-assets.ts')
const ASSETS_SKILL = 'web-access'
const ASSETS_DIR = join(SKILLS_DIR, 'standard', ASSETS_SKILL)

interface BundledSkill {
  type: 'standard' | 'mipham'
  raw: string
}

interface BundledSkillAsset {
  path: string
  content: string
  mode?: number
}

function collect(dir: string, type: 'standard' | 'mipham', ext: string): BundledSkill[] {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(ext))
    .sort()
  return files.map((f) => ({
    type,
    raw: readFileSync(join(dir, f), 'utf-8'),
  }))
}

/** Recursively collect executable assets; path is `/`-joined relative to `dir`.
 *  Content is UTF-8 text only — binary assets would need base64. */
function collectAssets(dir: string): BundledSkillAsset[] {
  const out: BundledSkillAsset[] = []
  const walk = (d: string, rel: string): void => {
    for (const name of readdirSync(d).sort()) {
      if (name === '.gitkeep' || name === '.git') continue
      const full = join(d, name)
      const relPath = rel ? `${rel}/${name}` : name
      const st = statSync(full)
      if (st.isDirectory()) walk(full, relPath)
      else out.push({ path: relPath, content: readFileSync(full, 'utf-8'), mode: st.mode & 0o777 })
    }
  }
  walk(dir, '')
  return out
}

function main(): void {
  const standard = collect(join(SKILLS_DIR, 'standard'), 'standard', '.SKILL.md')
  const mipham = collect(join(SKILLS_DIR, 'mipham'), 'mipham', '.mipham-skill.md')
  const all = [...standard, ...mipham]

  const lines: string[] = [
    '// AUTO-GENERATED by scripts/generate-bundled-skills.ts — DO NOT EDIT.',
    '// Regenerate with: bun run scripts/generate-bundled-skills.ts',
    '// In-memory snapshot of the built-in skills, embedded into the compiled binary.',
    '',
    'export interface BundledSkill {',
    "  type: 'standard' | 'mipham'",
    '  raw: string',
    '}',
    '',
    'export const BUNDLED_SKILLS: ReadonlyArray<BundledSkill> = [',
  ]
  for (const s of all) {
    lines.push(`  { type: '${s.type}', raw: ${JSON.stringify(s.raw)} },`)
  }
  lines.push(']')
  lines.push('')
  writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8')

  const assets = collectAssets(ASSETS_DIR)
  const assetLines: string[] = [
    '// AUTO-GENERATED by scripts/generate-bundled-skills.ts — DO NOT EDIT.',
    '// Regenerate with: bun run scripts/generate-bundled-skills.ts',
    '// In-memory snapshot of built-in skills that ship executable assets.',
    '',
    'export interface BundledSkillAsset {',
    '  path: string',
    '  content: string',
    '  mode?: number',
    '}',
    '',
    'export const BUNDLED_SKILL_ASSETS: Record<string, BundledSkillAsset[]> = {',
    `  ${JSON.stringify(ASSETS_SKILL)}: [`,
    ...assets.map(
      (a) =>
        `    { path: ${JSON.stringify(a.path)}, content: ${JSON.stringify(a.content)}, mode: ${a.mode} },`,
    ),
    '  ],',
    '}',
    '',
  ]
  writeFileSync(ASSETS_OUTPUT_FILE, assetLines.join('\n'), 'utf-8')

  console.log(
    `Generated ${OUTPUT_FILE} with ${all.length} skills (${standard.length} standard, ${mipham.length} mipham)`,
  )
  console.log(`Generated ${ASSETS_OUTPUT_FILE} with ${assets.length} assets for "${ASSETS_SKILL}"`)
}

main()
