# Mipham Code — Homebrew Formula
#
# To install locally for testing:
#   brew install --build-from-source ./infrastructure/brew/mipham.rb
#
# To submit to homebrew-core:
#   1. Fork https://github.com/Homebrew/homebrew-core
#   2. Add this file to Formula/m/mipham.rb
#   3. Submit PR with bottle block (generated by brew test-bot)
class Mipham < Formula
  desc "Multi-model open-core intelligent coding terminal"
  homepage "https://mipham.ai/code"
  url "https://registry.npmjs.org/@mipham/cli/-/cli-0.1.0.tgz"
  sha256 "PLACEHOLDER" # Run: curl -sL <url> | shasum -a 256
  license "Apache-2.0"
  version "0.1.0"

  depends_on "bun"
  depends_on "node"

  def install
    # Install the npm package globally into the prefix
    system "npm", "install", "-g", "--prefix", prefix, "@mipham/cli@#{version}"

    # Create symlink from bin/mipham to the npm global bin
    bin.install_symlink Dir[prefix/"bin/mipham"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mipham --version")
  end
end
